<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_4</name>
   <tag></tag>
   <elementGuidId>616bd3e7-79bf-430f-a590-eac9ad24df39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='screen']/div/div/div[3]/app-defect-counter/div/div/span[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.projects-counter.defects.ng-star-inserted > div.counter-inner > span.counted-number > a.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f0e42e8d-34b5-4c7d-b21e-e2bb068c3440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/defect</value>
      <webElementGuid>ec489868-84fa-444d-9293-e9b7dc89a823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>f6ee86cd-a600-4750-973d-f97467f62b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>330cecec-03a8-41b4-b438-96954df14de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;screen&quot;)/div[@class=&quot;dashboard-row&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg counter&quot;]/app-defect-counter[1]/div[@class=&quot;projects-counter defects ng-star-inserted&quot;]/div[@class=&quot;counter-inner&quot;]/span[@class=&quot;counted-number&quot;]/a[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>aa71f3d8-1373-4aa9-99f6-231ffeff8738</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='screen']/div/div/div[3]/app-defect-counter/div/div/span[2]/a</value>
      <webElementGuid>9824c3c0-16f3-4dcc-8822-c05443a13256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'4')]</value>
      <webElementGuid>3ff562a4-bf54-4798-a283-96ac004d429f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/defect')])[5]</value>
      <webElementGuid>bcb657f4-b192-4369-9d17-45063e5f14a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>61d77792-c60b-4ed0-b046-a65a9d003b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/defect' and (text() = '4' or . = '4')]</value>
      <webElementGuid>07039415-ae5d-4d60-84e4-e4850869273d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
