<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DEF-272286</name>
   <tag></tag>
   <elementGuidId>e201c30e-d291-4f4b-bafb-b3d868b4e557</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'DEF-272286')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.defectIdWrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ebc80a9e-1426-4237-8e04-55cfed7c773a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>bd015fa3-c2e2-4a25-b216-8eb57714905e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/defect/detail/272286</value>
      <webElementGuid>6299d9c2-4dd7-4b71-b704-e4dca7c9fac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>defectIdWrap</value>
      <webElementGuid>2c07b51c-c084-4043-b8a2-937060376682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DEF-272286</value>
      <webElementGuid>08481d8f-f875-4111-8106-aab70fd863fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography dialog-open&quot;]/app-root[1]/block-ui[1]/app-dashboard-list[1]/app-layout[1]/div[@class=&quot;ng-main-wrapper&quot;]/div[@class=&quot;content-wrapper ng-star-inserted&quot;]/app-defect-list-quick-view[1]/app-popup-modal[@class=&quot;quickListModal&quot;]/ngx-smart-modal[1]/div[@class=&quot;overlay ng-star-inserted nsm-overlay-open&quot;]/div[@class=&quot;nsm-dialog nsm-dialog-animation-fade nsm-dialog-open&quot;]/div[@class=&quot;nsm-content&quot;]/div[@class=&quot;nsm-body&quot;]/div[@class=&quot;add_user_model add_user_model_two cus-width ng-star-inserted&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;p-pad-wrapper mt-2&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;siteTableWrapper table-responsive&quot;]/table[@class=&quot;table table-bordered siteTable&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[1]/a[@class=&quot;defectIdWrap&quot;]</value>
      <webElementGuid>11de19ef-2407-408a-a899-81c4ef4599a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DEF-272286')]</value>
      <webElementGuid>f54efd62-950a-4f05-9c5e-444cabdd0273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/defect/detail/272286')]</value>
      <webElementGuid>f295c7b7-9d0d-4af3-a55c-b7610995872d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>dfa3707b-c4dc-4c57-a5a2-cce20fa755f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/defect/detail/272286' and (text() = 'DEF-272286' or . = 'DEF-272286')]</value>
      <webElementGuid>3e70b9e3-7059-4aaa-8a50-d9d19b2d14b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
