<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_New Defect</name>
   <tag></tag>
   <elementGuidId>dd4ee459-3ae4-437d-92c0-13d562258616</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='tour-defect-create-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tour-defect-create-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>268fe5a9-1b20-4ed5-b7cb-fde24437d734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tour-defect-create-btn</value>
      <webElementGuid>b5dce921-0132-4fef-9b4b-69fdab58c0b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:</value>
      <webElementGuid>16e29247-2b65-4256-89ee-642b13a23bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>d7d1aa51-0358-483d-9044-2d4460ac7c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>create-button ng-star-inserted</value>
      <webElementGuid>ddee4842-610b-49c0-bfb5-c03cb21aec60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> New Defect </value>
      <webElementGuid>72c55de9-4d5c-4fa1-b373-01e641e39a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tour-defect-create-btn&quot;)</value>
      <webElementGuid>c5917f52-46fc-44a2-beed-0df68156f259</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='tour-defect-create-btn']</value>
      <webElementGuid>74eec9c8-be88-4f44-bd44-69be21e604de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'New Defect')])[2]</value>
      <webElementGuid>ff1271ba-c65a-41c5-b159-ffc8ab2c9471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:')])[13]</value>
      <webElementGuid>827fccfe-5117-4402-b6ca-aee8bb2c1b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a</value>
      <webElementGuid>2afbb70f-fb58-4ce2-b39d-9395e89c7bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'tour-defect-create-btn' and @href = 'javascript:' and (text() = ' New Defect ' or . = ' New Defect ')]</value>
      <webElementGuid>cdd0e1cf-3fda-4d1a-b6e0-f71e083b6c13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
