<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_New Test Case</name>
   <tag></tag>
   <elementGuidId>97dd87cf-99a0-4cb1-9787-3b91f20d43ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='tour-test-case-create-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tour-test-case-create-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2cc5023c-b442-4c1c-b2c1-bc2507067ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tour-test-case-create-btn</value>
      <webElementGuid>4ad3b61d-fb9c-4e90-b3a8-6176998e96c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:</value>
      <webElementGuid>0cb3b329-d60b-402e-a2f6-83750c91eff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>c604eab1-3821-4824-8b61-5a45d613d7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>create-button ng-star-inserted</value>
      <webElementGuid>75ffef77-55b4-4b1d-ac89-6995f0255750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Test Case </value>
      <webElementGuid>e857156f-75ef-4cd8-b3d7-e1c9be70a576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tour-test-case-create-btn&quot;)</value>
      <webElementGuid>0a6ec49d-28f7-4be4-8b9a-c7f73078890c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='tour-test-case-create-btn']</value>
      <webElementGuid>39b0a414-197f-41bc-8096-1b76fb8d1841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'New Test Case')])[2]</value>
      <webElementGuid>80f1d816-d38e-45c1-8499-90292d97a357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:')])[13]</value>
      <webElementGuid>46d1cc89-5196-4a02-8032-f2d8a457a72a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a</value>
      <webElementGuid>11ead1bc-2f0b-4f0e-9a9f-3129be57c234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'tour-test-case-create-btn' and @href = 'javascript:' and (text() = 'New Test Case ' or . = 'New Test Case ')]</value>
      <webElementGuid>282e0756-a2b0-4572-a271-47cef843ab6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
