<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_New Test Case</name>
   <tag></tag>
   <elementGuidId>97dd87cf-99a0-4cb1-9787-3b91f20d43ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='tour-test-case-create-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tour-test-case-create-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>80720073-605c-4427-bbf2-8eda19cd6a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tour-test-case-create-btn</value>
      <webElementGuid>1c8e7c78-d045-4201-b0ea-ce8579554399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:</value>
      <webElementGuid>9af01029-3945-4d1d-b3d4-cf72ce5c44a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>e918b624-a336-4fea-9741-6e835486a7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>create-button ng-star-inserted</value>
      <webElementGuid>b16f3624-a467-42a4-9ce0-c5a00c0784c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Test Case </value>
      <webElementGuid>155080e5-9762-4c65-ba79-a1db00aaac98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tour-test-case-create-btn&quot;)</value>
      <webElementGuid>148e4a94-ee04-4872-a2e3-3f6dee2eb3ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='tour-test-case-create-btn']</value>
      <webElementGuid>94e5a886-afd7-4a1c-97f7-62e8c9f4377a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'New Test Case')])[2]</value>
      <webElementGuid>11a4baa3-15f9-412e-86c2-c99eedf5fc62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:')])[13]</value>
      <webElementGuid>78da9585-a31d-43eb-b949-c91228007c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a</value>
      <webElementGuid>eef017c7-5215-4b97-8ef8-00674f120e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'tour-test-case-create-btn' and @href = 'javascript:' and (text() = 'New Test Case ' or . = 'New Test Case ')]</value>
      <webElementGuid>50767629-f2fe-44c0-9eac-5004000ecfff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
