<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update</name>
   <tag></tag>
   <elementGuidId>4937a7fa-fe72-4d17-a3d6-a67341d70106</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.submit-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9ea75912-06ec-4b2c-8738-43ef85c76280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit-btn</value>
      <webElementGuid>33b637fa-adca-4013-8f7c-967975ac65c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update </value>
      <webElementGuid>68c56a16-3eb6-4f15-a7d0-f25e618214c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/block-ui[1]/app-defect-list[@class=&quot;ng-star-inserted&quot;]/app-layout[1]/div[@class=&quot;ng-main-wrapper&quot;]/div[@class=&quot;content-wrapper ng-star-inserted&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;overlaySidePanel&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-defect-edit-overlay[1]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content-holder clearfix&quot;]/div[@class=&quot;create-project-form editdefectPage&quot;]/form[@class=&quot;ng-valid ng-dirty ng-touched&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;form-row&quot;]/div[@class=&quot;form-buttons clearfix btn-group&quot;]/button[@class=&quot;submit-btn&quot;]</value>
      <webElementGuid>487faa7d-1a5c-472c-b3a8-546ce97f6d91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/button</value>
      <webElementGuid>8e613f4f-cc10-46ea-977b-26e273df1621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Update ' or . = 'Update ')]</value>
      <webElementGuid>aba78b53-7ed7-4219-9187-57e88c65eb71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
