<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>edd8d71d-fc21-4fbf-b358-7ad2f6df3011</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='test-create-submit-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#test-create-submit-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e6b6f314-dadf-4478-a20b-05153509de26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>test-create-submit-btn</value>
      <webElementGuid>3d8b75d3-c958-4121-95dd-3e1e21022049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit-btn ng-tns-c130-13</value>
      <webElementGuid>9657eb3d-9cc7-4947-86db-821e21ded3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Save </value>
      <webElementGuid>b29237f8-4c0f-4101-ab7f-db18e784c5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/block-ui[1]/app-test-case-create[@class=&quot;ng-tns-c130-13 ng-star-inserted&quot;]/app-layout[@class=&quot;ng-tns-c130-13&quot;]/div[@class=&quot;ng-main-wrapper&quot;]/div[@class=&quot;content-wrapper ng-tns-c130-13 ng-star-inserted&quot;]/div[@class=&quot;clearfix ng-tns-c130-13&quot;]/div[@class=&quot;create-project-form createTestCasePage ng-tns-c130-13&quot;]/div[@class=&quot;container ng-tns-c130-13&quot;]/form[@class=&quot;ng-tns-c130-13 ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;col-12 ng-tns-c130-13&quot;]/div[@class=&quot;form-buttons clearfix btn-group ng-tns-c130-13&quot;]/button[@id=&quot;test-create-submit-btn&quot;]</value>
      <webElementGuid>1a84125a-06a6-4135-96bd-19471797955a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='test-create-submit-btn']</value>
      <webElementGuid>29cd4c97-fe99-4594-84b2-7b582c9ca02e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>565a0f44-d967-49a4-8258-0fea338111da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'test-create-submit-btn' and (text() = ' Save ' or . = ' Save ')]</value>
      <webElementGuid>fbf852a8-834d-41ac-b89c-3e0942c14d66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
