<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>edd8d71d-fc21-4fbf-b358-7ad2f6df3011</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='test-create-submit-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#test-create-submit-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a631cd15-abed-4d96-860b-e8dc63077141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>test-create-submit-btn</value>
      <webElementGuid>6a6ab9af-25d9-4471-b911-db517017cf6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit-btn ng-tns-c127-13</value>
      <webElementGuid>e66a7664-607d-43c7-99ef-5b04cc98b678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Save </value>
      <webElementGuid>4062fa91-5d83-440a-811b-220db5c73e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/block-ui[1]/app-test-case-create[@class=&quot;ng-tns-c127-13 ng-star-inserted&quot;]/app-layout[@class=&quot;ng-tns-c127-13&quot;]/div[@class=&quot;ng-main-wrapper&quot;]/div[@class=&quot;content-wrapper ng-tns-c127-13 ng-star-inserted&quot;]/div[@class=&quot;clearfix ng-tns-c127-13&quot;]/div[@class=&quot;create-project-form createTestCasePage ng-tns-c127-13&quot;]/div[@class=&quot;container ng-tns-c127-13&quot;]/form[@class=&quot;ng-tns-c127-13 ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;col-12 ng-tns-c127-13&quot;]/div[@class=&quot;form-buttons clearfix btn-group ng-tns-c127-13&quot;]/button[@id=&quot;test-create-submit-btn&quot;]</value>
      <webElementGuid>0457b832-e519-424f-aa06-641410653739</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='test-create-submit-btn']</value>
      <webElementGuid>a61a78d8-3225-42aa-96d8-8c82fb1c8186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>2fecc37e-b5ed-4a27-b0d1-304a13e0900f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'test-create-submit-btn' and (text() = ' Save ' or . = ' Save ')]</value>
      <webElementGuid>49eec7bd-0eac-41d1-b51e-fa46fc3abfa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
