<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LoginEmail PASSWORD  Keep me signed in._eb1ffa</name>
   <tag></tag>
   <elementGuidId>d660a41f-1c7e-489a-83d3-46c0cd5fad3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.login-visual</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>545b1714-7270-4521-90a7-a9598540f875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-visual</value>
      <webElementGuid>3adc6537-d234-49ed-bb56-a0a9a1f4e456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LoginEmail *PASSWORD * Keep me signed in. Forgot Password?Or Login with SSO Login with Azure AD Login with Google SAML login with Okta</value>
      <webElementGuid>d5a72a43-4025-4fd0-adbe-02c9112a75b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/block-ui[1]/app-login[1]/div[@class=&quot;login-wrapper clearfix&quot;]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;login-visual&quot;]</value>
      <webElementGuid>ea05f07e-dc7e-405b-a915-729ba14f2f65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div</value>
      <webElementGuid>b28513fa-870d-455d-8e7f-f9ef05e0fcec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'LoginEmail *PASSWORD * Keep me signed in. Forgot Password?Or Login with SSO Login with Azure AD Login with Google SAML login with Okta' or . = 'LoginEmail *PASSWORD * Keep me signed in. Forgot Password?Or Login with SSO Login with Azure AD Login with Google SAML login with Okta')]</value>
      <webElementGuid>c1a1e35d-f169-4907-8814-71d605ddd9cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
