<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_RequirementSelect RequirementTest Scena_7d154f</name>
   <tag></tag>
   <elementGuidId>44fffab4-966d-4bbe-83f2-4d2f718f0114</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>41ff859b-f4f2-40aa-8ceb-d87b9a3541b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>32cd416e-59fd-4f40-95e0-098b7346304f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RequirementSelect RequirementTest ScenarioSelect Test ScenarioTesting TypeSelect Testing Type3 Testing Type2 Testing Type1 Field Validation Content Cross Browser/OS UI/UX Security Performance FunctionalExecution TypeSelect Execution Type3 Execution Type2 Execution Type1 cypress automated manualPrioritySelect Priority3  Priority2  Priority1  Low  Medium  High Request Approval FromSelect provf  sheema  faran.khurshid+0002 Assign ToSelect User provf sheema faran.khurshid+0002ApplyCancel</value>
      <webElementGuid>642e3140-41d2-4b57-9ccd-265790391dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography dialog-open&quot;]/app-root[1]/block-ui[1]/app-test-case-list[@class=&quot;ng-star-inserted&quot;]/app-layout[1]/div[@class=&quot;ng-main-wrapper&quot;]/div[@class=&quot;content-wrapper ng-star-inserted&quot;]/div[@class=&quot;clearfix&quot;]/div[1]/app-popup-modal[1]/ngx-smart-modal[1]/div[@class=&quot;overlay ng-star-inserted nsm-overlay-open&quot;]/div[@class=&quot;nsm-dialog nsm-dialog-animation-fade nsm-dialog-open&quot;]/div[@class=&quot;nsm-content&quot;]/div[@class=&quot;nsm-body&quot;]/div[@class=&quot;add_user_model add_user_model_two&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;popup_margin_wrapper&quot;]/form[@class=&quot;ng-valid ng-dirty ng-touched&quot;]/div[@class=&quot;row&quot;]</value>
      <webElementGuid>7bafe8b6-4075-45a6-b455-95bfcff21a64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]</value>
      <webElementGuid>897e1c22-473c-4a23-8035-17081f47bf13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'RequirementSelect RequirementTest ScenarioSelect Test ScenarioTesting TypeSelect Testing Type3 Testing Type2 Testing Type1 Field Validation Content Cross Browser/OS UI/UX Security Performance FunctionalExecution TypeSelect Execution Type3 Execution Type2 Execution Type1 cypress automated manualPrioritySelect Priority3  Priority2  Priority1  Low  Medium  High Request Approval FromSelect provf  sheema  faran.khurshid+0002 Assign ToSelect User provf sheema faran.khurshid+0002ApplyCancel' or . = 'RequirementSelect RequirementTest ScenarioSelect Test ScenarioTesting TypeSelect Testing Type3 Testing Type2 Testing Type1 Field Validation Content Cross Browser/OS UI/UX Security Performance FunctionalExecution TypeSelect Execution Type3 Execution Type2 Execution Type1 cypress automated manualPrioritySelect Priority3  Priority2  Priority1  Low  Medium  High Request Approval FromSelect provf  sheema  faran.khurshid+0002 Assign ToSelect User provf sheema faran.khurshid+0002ApplyCancel')]</value>
      <webElementGuid>dd90cc86-50f6-4741-a585-9754575803c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
