<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_block-ui-wrapper block-ui-main active</name>
   <tag></tag>
   <elementGuidId>7502b182-2a68-492c-93a9-282d940504a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//block-ui-content/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.block-ui-wrapper.block-ui-main.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>707e73dc-0b5b-440c-b2a4-c2514f325dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block-ui-wrapper block-ui-main active</value>
      <webElementGuid>7f2dcef6-bec4-4375-aeb0-54dd0e19e310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/block-ui[1]/block-ui-content[1]/div[@class=&quot;block-ui-wrapper block-ui-main active&quot;]</value>
      <webElementGuid>8e6e9ac6-106d-4fc9-ac4c-46a2caf8321c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//block-ui-content/div</value>
      <webElementGuid>4dedb9a1-7616-435c-915b-8115066935d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
