<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_fa-solid fa-times</name>
   <tag></tag>
   <elementGuidId>0ac00b18-76e0-4b01-b9c5-a7eb99e83a0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa-solid.fa-times</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ec6c3549-297f-415f-9a70-825bc097eb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8623f060-cdd2-439b-8cac-3dab413e03da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-solid fa-times</value>
      <webElementGuid>f7f3ed52-a736-4e09-a473-e026f5daac75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/block-ui[1]/app-test-case-list[@class=&quot;ng-star-inserted&quot;]/app-layout[1]/app-footer[1]/div[@class=&quot;clearfix footer-holder ng-star-inserted&quot;]/div[@class=&quot;footer-right&quot;]/app-user-check-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;checkListBox active ng-star-inserted&quot;]/button[@class=&quot;checkListClose&quot;]/i[@class=&quot;fa-solid fa-times&quot;]</value>
      <webElementGuid>67afcf8c-8132-4b86-81f1-b03b44dba9d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>89060d09-66ad-4ea5-8137-cc201e8299ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
