<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tc_name</name>
   <tag></tag>
   <elementGuidId>93dca043-5a97-40a1-b617-ba8d7e5b0254</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tc_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tc_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b251bd42-7fc5-40ce-9c87-a035ae2dad53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tc_name</value>
      <webElementGuid>a2964441-aa90-4d2e-a673-fe8f31c07ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2ad26019-9a30-4fcc-8207-ca909eb20ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tc_name</value>
      <webElementGuid>9758ea67-d087-4a7d-bbeb-7c3f06997804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control test-case-form-validation ng-tns-c127-13 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>073ca754-54b5-4424-a83e-2884a8983895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tc_name&quot;)</value>
      <webElementGuid>b8d5db24-22e3-41cb-9584-e4f8f19df01f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tc_name']</value>
      <webElementGuid>887d5a23-fa6a-4c45-9caa-9121870696ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>f842517a-a110-4754-8cc3-210c68a68d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tc_name' and @type = 'text' and @name = 'tc_name']</value>
      <webElementGuid>9ba3391a-4ed5-4e30-97ba-48501f788690</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
