<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tc_name</name>
   <tag></tag>
   <elementGuidId>93dca043-5a97-40a1-b617-ba8d7e5b0254</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tc_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tc_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d89a53b9-9e94-4bef-b9b4-093f47e1919a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tc_name</value>
      <webElementGuid>017ba7e6-4dd1-4ccd-90b4-f06334efbccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ef72d04-c772-401d-b996-0e0a08fdf386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tc_name</value>
      <webElementGuid>2ab56c83-ebb8-46e9-8ea9-c622bf7dfc93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control test-case-form-validation ng-tns-c130-13 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>c369e0c1-ba93-415c-97af-730a8ecec979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tc_name&quot;)</value>
      <webElementGuid>55b0a6a0-7230-40be-b433-32dd52bde118</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tc_name']</value>
      <webElementGuid>256923e7-42e9-468a-8049-84af6b327e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>65b766ab-5c71-4984-a384-8cc758989b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tc_name' and @type = 'text' and @name = 'tc_name']</value>
      <webElementGuid>1dedfa57-7a18-434b-be68-dfd4c4af89ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
