<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_time</name>
   <tag></tag>
   <elementGuidId>4b66b1f2-fd94-4318-a64c-57cc1e4af5e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='time']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#time</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4f7c7ab-c3db-49f0-8af7-b24f6e5068fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>time</value>
      <webElementGuid>013f1f6b-7594-40ba-9c91-625595fac465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5714a960-7a0d-42bd-b60d-c2e6947f8714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>time</value>
      <webElementGuid>1ea2993c-6226-4663-aa6f-ce400f67696e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>HH:MM</value>
      <webElementGuid>5fb25b70-ebfb-465d-b1bd-59aae067a429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-tns-c127-13 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>37256f04-6a2e-4448-8b09-db589538f471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;time&quot;)</value>
      <webElementGuid>a98d588f-dc7d-40da-85c9-11df2247ffc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='time']</value>
      <webElementGuid>9ac14729-0a62-4fde-9d91-d42ca80e473f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/input</value>
      <webElementGuid>74050b71-113f-4921-a113-467e68b700df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'time' and @type = 'text' and @name = 'time' and @placeholder = 'HH:MM']</value>
      <webElementGuid>8d7563e5-205b-4603-8072-4fcabf8d453a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
