<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectOpen Tasks Ongoing Tasks Compl_640ee5</name>
   <tag></tag>
   <elementGuidId>b360b3a2-167b-4595-8ada-9bfc2b7e8b71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='column_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#column_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bf59f2af-a462-4cfd-86f5-03948a57c396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>column_id</value>
      <webElementGuid>d3be296b-57f5-4fcf-b7ed-7bb50e41f12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>column_id</value>
      <webElementGuid>01f610c5-cf17-467d-a98e-c03760b65f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-tns-c127-13 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>50f64da8-0a3e-48e4-bf37-ae2e09984d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectOpen Tasks Ongoing Tasks Completed Tasks Tasks on Hold </value>
      <webElementGuid>446e607c-a5ba-43d1-bbf4-66b411c3082c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;column_id&quot;)</value>
      <webElementGuid>a351efcc-70e2-41d1-b3f6-01d19d522ce1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='column_id']</value>
      <webElementGuid>cdc49260-6215-4ae3-89d5-679fbec0e785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/select</value>
      <webElementGuid>af90bca4-7a92-4800-bda1-62e7788af9b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'column_id' and @name = 'column_id' and (text() = 'SelectOpen Tasks Ongoing Tasks Completed Tasks Tasks on Hold ' or . = 'SelectOpen Tasks Ongoing Tasks Completed Tasks Tasks on Hold ')]</value>
      <webElementGuid>ec8a5747-2d93-46d0-8635-7da1385df849</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
