<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Assign To provf faran.khurshid0002</name>
   <tag></tag>
   <elementGuidId>666aa856-83a6-4c69-a4f1-88b5beb6a210</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#assignedto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='assignedto']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ec81e4b0-8187-47f5-93e4-0c3e7e4cf7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>assignedto</value>
      <webElementGuid>26c471a3-adc1-4cfd-b2d4-13840b69b72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assignedto</value>
      <webElementGuid>fb1fa7f1-301f-463e-9216-5da744a77861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Assign To</value>
      <webElementGuid>b14fdae4-11a7-45ba-ab7f-ad681e4f3144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine is-invalid ng-invalid</value>
      <webElementGuid>8305cd7b-ce97-4f26-b435-e23360549fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assign To provf faran.khurshid+0002</value>
      <webElementGuid>d911d003-b18d-4918-90d4-ff113620da14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assignedto&quot;)</value>
      <webElementGuid>847f9ea1-6386-4035-8f99-25ef654543e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='assignedto']</value>
      <webElementGuid>86372c2e-5e0f-4306-9ef1-8bd03a70ac7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div/div/select</value>
      <webElementGuid>2d4dd363-fcd9-4b0b-89d8-6b033e4851a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'assignedto' and @name = 'assignedto' and @placeholder = 'Assign To' and (text() = 'Assign To provf faran.khurshid+0002' or . = 'Assign To provf faran.khurshid+0002')]</value>
      <webElementGuid>b162b843-519e-45ff-8c16-7858d7f73548</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
