<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Selectmod1module1</name>
   <tag></tag>
   <elementGuidId>6b8e2d54-258d-478f-a1f8-fdcb0a7737a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='module_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#module_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e8870417-6111-4936-86ba-4fb9112ae081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>module_id</value>
      <webElementGuid>99561a8d-f169-4b2c-b0b9-ecf0761a3107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>module_id</value>
      <webElementGuid>ad1fd92e-ff3f-41c5-9fd4-eced73831a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-tns-c127-13 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c8756c32-94e7-4114-bc47-1270ef90fe42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selectmod1module1</value>
      <webElementGuid>29ee5924-e616-41c0-99b0-e760bbbef876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;module_id&quot;)</value>
      <webElementGuid>223771ab-6e8a-4204-8732-4007e13ecce6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='module_id']</value>
      <webElementGuid>0e1ed23a-740e-4c30-ae0c-48f6092466db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>d2613411-821e-4b14-ab8c-66bae40b23d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'module_id' and @name = 'module_id' and (text() = 'Selectmod1module1' or . = 'Selectmod1module1')]</value>
      <webElementGuid>b7bb5a66-8efb-420f-aa28-fa0697117ab5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
