<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Blocker Major Minor</name>
   <tag></tag>
   <elementGuidId>94acb5f9-7dc8-404f-85f4-93a8ebee761f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='severity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#severity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c17351d3-da9c-466d-b3ab-437b3dd256de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>severity</value>
      <webElementGuid>23bfbf46-7ddb-49a0-a82f-a6bd63ba24a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>severity</value>
      <webElementGuid>4e75926a-ad9f-4471-b9ca-63aff775d0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>305b752b-5b9b-4cf5-bcd8-9c0f92a8b406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Blocker Major Minor</value>
      <webElementGuid>44404413-14cc-4b99-93ba-ea792e291049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;severity&quot;)</value>
      <webElementGuid>c8d22e18-3f2d-4c7c-a063-b56465444cb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='severity']</value>
      <webElementGuid>f4ba298a-d0ba-4f1f-9340-42386cb51ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/select</value>
      <webElementGuid>391139f3-e9ed-4aab-b393-6340a6eda84b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'severity' and @name = 'severity' and (text() = 'Select Blocker Major Minor' or . = 'Select Blocker Major Minor')]</value>
      <webElementGuid>80aba94f-fe04-49cf-bbef-2604a1cea81a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
