<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Test Scenario name 1 Test Sce_cf48c7</name>
   <tag></tag>
   <elementGuidId>e424a03d-96fa-4c1f-a53e-fbcdd9e24291</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tc_scenario_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tc_scenario_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>40c5453a-d42c-4db8-8c24-ecd298ddbce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tc_scenario_id</value>
      <webElementGuid>95d1ac0d-3f3c-4b90-bdab-e7c3a1c37097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tc_scenario_id</value>
      <webElementGuid>29139db5-d707-4176-a92c-00c2e6abd444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-tns-c127-13 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>449495b6-119b-4c68-bd1b-1d6260e059c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Test Scenario name 1 Test Scenario name 1</value>
      <webElementGuid>9181db9b-7a4a-42b7-a6ef-03a328de8405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tc_scenario_id&quot;)</value>
      <webElementGuid>14dd7a8a-d15f-45ef-a16e-8d2e57516611</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tc_scenario_id']</value>
      <webElementGuid>87d81f2a-e253-47ec-9a88-2b71bad6f550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/select</value>
      <webElementGuid>d8b55c77-42ac-4597-a2d8-11f7ddd2d9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'tc_scenario_id' and @name = 'tc_scenario_id' and (text() = 'Select Test Scenario name 1 Test Scenario name 1' or . = 'Select Test Scenario name 1 Test Scenario name 1')]</value>
      <webElementGuid>9ddd962a-7c17-49c3-ac75-ed689fd2d825</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
