<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Priority3  Priority2  Priorit_f0f572</name>
   <tag></tag>
   <elementGuidId>ca4cb430-aee9-4b05-829f-987fc091c571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tc_priority']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tc_priority</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>89eb03b0-cc5d-44e0-a4e5-ed69ff69cb67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tc_priority</value>
      <webElementGuid>7e487da8-15d9-486e-9955-ac2fe8aaf1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tc_priority</value>
      <webElementGuid>a828c7c6-fba7-4e47-aa35-16fc5b521557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-tns-c127-13 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b02fe72e-fbf2-48e8-82e9-6d8fc829e016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Priority3  Priority2  Priority1  Low  Medium  High </value>
      <webElementGuid>cc33ebfa-6c4a-49a3-9c99-45d0a1003aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tc_priority&quot;)</value>
      <webElementGuid>da2f476e-6b8b-429b-9c80-4b7d0dea0be9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tc_priority']</value>
      <webElementGuid>e0fd1cb6-d865-47d3-a0dd-e67f53c6e33c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/select</value>
      <webElementGuid>55b5e695-ca26-4fd8-8923-2687de159acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'tc_priority' and @name = 'tc_priority' and (text() = 'Select Priority3  Priority2  Priority1  Low  Medium  High ' or . = 'Select Priority3  Priority2  Priority1  Low  Medium  High ')]</value>
      <webElementGuid>c3f7e33e-5caf-4adf-9d77-5e2f0c3b5dc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
