<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select BuildBuild2 Build3 build1</name>
   <tag></tag>
   <elementGuidId>13a87a00-6d2b-4900-98d6-adbf9aeac78b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='bulk_action_build_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bulk_action_build_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>348ba6c5-ff05-46d7-a16d-6e3c19ed04d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bulk_action_build_id</value>
      <webElementGuid>3f963f71-1e7f-4e37-b951-01ab4ebb85cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bulk_action_build_id</value>
      <webElementGuid>d9ff31ca-7099-463d-b246-c9aacfa87022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Build</value>
      <webElementGuid>949feecb-a556-40fb-9240-28aab0619afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>ada88dc4-3519-4919-9d99-62041a32c546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select BuildBuild2 Build3 build1 </value>
      <webElementGuid>50247a61-c1b1-4bdf-96c5-083d1674cc3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bulk_action_build_id&quot;)</value>
      <webElementGuid>f318bbc2-1b19-49e6-81a7-6cafb3fa0ac0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='bulk_action_build_id']</value>
      <webElementGuid>c7f2e047-5f6d-45eb-b65f-1796c016c76e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/select</value>
      <webElementGuid>698b1c72-8b93-4a90-a866-cefa995def7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'bulk_action_build_id' and @name = 'bulk_action_build_id' and @placeholder = 'Select Build' and (text() = 'Select BuildBuild2 Build3 build1 ' or . = 'Select BuildBuild2 Build3 build1 ')]</value>
      <webElementGuid>10a05b61-3512-46ca-b548-9a3b42698e4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
