<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectBuild2Build3build1</name>
   <tag></tag>
   <elementGuidId>a6697868-cd42-4d62-a929-3f58940cabae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='build_id'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-group > div.cssOptions > #build_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a105f62c-c0c0-49a2-bff2-819ae634b0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>build_id</value>
      <webElementGuid>5f28224d-d1bb-40ad-8676-a5ecfdbf7e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>build_id</value>
      <webElementGuid>ba7a72a6-91a3-47e6-88b5-580f42fb8a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>6e35741f-dae4-4b8b-accc-76deb3cf1b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectBuild2Build3build1</value>
      <webElementGuid>1589efc3-d86c-4876-b8ed-8907900d1b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/block-ui[1]/app-defect-list[@class=&quot;ng-star-inserted&quot;]/app-layout[1]/div[@class=&quot;ng-main-wrapper&quot;]/div[@class=&quot;content-wrapper ng-star-inserted&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;overlaySidePanel&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-defect-edit-overlay[1]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content-holder clearfix&quot;]/div[@class=&quot;create-project-form editdefectPage&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 col-lg-6&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;cssOptions&quot;]/select[@id=&quot;build_id&quot;]</value>
      <webElementGuid>db02303e-98a1-4ded-8196-512ebc083081</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='build_id'])[2]</value>
      <webElementGuid>50d74dc2-41d3-4a3c-ae1f-a755c447ab33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/select</value>
      <webElementGuid>53364695-851b-4661-b34b-e9927abc3564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'build_id' and @name = 'build_id' and (text() = 'SelectBuild2Build3build1' or . = 'SelectBuild2Build3build1')]</value>
      <webElementGuid>5a7d8fe8-cf25-413b-924f-a38570b0da65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
