<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Testing Type3 Testing Type2 T_73554a</name>
   <tag></tag>
   <elementGuidId>8e2172ad-ffc9-4f2c-9f82-733cdea97708</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tc_testing_type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tc_testing_type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0fa76919-7b4f-4ed4-b9d1-c0803fe1d9e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tc_testing_type</value>
      <webElementGuid>51912b91-0506-4524-9891-73cfdeef338b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tc_testing_type</value>
      <webElementGuid>370825d4-2d7e-4a65-8868-0fc4f1a25ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-tns-c127-13 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>ba8d624f-f3d4-4372-83f3-8d53e4f90833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Testing Type3 Testing Type2 Testing Type1 Field Validation Content Cross Browser/OS UI/UX Security Performance Functional</value>
      <webElementGuid>b92617a8-67a0-46d9-b24e-e74d6e0cf1fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tc_testing_type&quot;)</value>
      <webElementGuid>a9fb348e-e175-4dc7-9d04-7fa3f2f63de8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tc_testing_type']</value>
      <webElementGuid>6fb4fe8a-6bc4-4fee-91f7-1e2e9edee100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/select</value>
      <webElementGuid>a0a9aa90-4a17-4930-9108-12c2e7002faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'tc_testing_type' and @name = 'tc_testing_type' and (text() = 'Select Testing Type3 Testing Type2 Testing Type1 Field Validation Content Cross Browser/OS UI/UX Security Performance Functional' or . = 'Select Testing Type3 Testing Type2 Testing Type1 Field Validation Content Cross Browser/OS UI/UX Security Performance Functional')]</value>
      <webElementGuid>6a0cac65-2eba-4f4a-82f0-fcc6fb6e14f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
