<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectBuild2 Build3 build1</name>
   <tag></tag>
   <elementGuidId>7fc02296-4b2c-4808-8ca6-8d2100dbfbf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='build_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#build_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>09421846-ea05-4190-a0b5-a495660dc2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>build_id</value>
      <webElementGuid>6f29f21f-0668-442a-b073-e9e6bcd5bbb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>build_id</value>
      <webElementGuid>e7ee7438-8c71-414c-b85c-ee67a0889090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-tns-c127-13 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>ec0c17de-d630-4064-9e65-274b886f4922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectBuild2 Build3 build1 </value>
      <webElementGuid>b7e484d6-1768-45e8-8876-e128d59c5750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;build_id&quot;)</value>
      <webElementGuid>122e6843-2df2-4554-80d4-636399bea31e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='build_id']</value>
      <webElementGuid>8861db9d-feeb-48c4-a6b6-fabd0edb9538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/select</value>
      <webElementGuid>6e88da8d-a4e2-4616-b622-a28838858194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'build_id' and @name = 'build_id' and (text() = 'SelectBuild2 Build3 build1 ' or . = 'SelectBuild2 Build3 build1 ')]</value>
      <webElementGuid>3e41e4a4-4cb7-4083-b252-5316d5096f75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
