<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectPending Approval Approved Rejected</name>
   <tag></tag>
   <elementGuidId>26cebfbc-bff2-492e-b060-78e8538a5250</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tc_status']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tc_status</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>70565c06-5b81-42d8-abe9-b06eea3e96de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tc_status</value>
      <webElementGuid>48dbbc35-f4a5-4265-82e4-934279f7951e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tc_status</value>
      <webElementGuid>c8beffcc-5969-4528-8f2a-787b149e3335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-tns-c127-13 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>909de784-6971-4ced-8d6e-6d05d986d391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectPending Approval Approved Rejected </value>
      <webElementGuid>b5a5f42b-0466-4a07-a357-bbeaae95ad1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tc_status&quot;)</value>
      <webElementGuid>72713b56-c8ae-40f3-a8f9-2490926b082b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tc_status']</value>
      <webElementGuid>f1fca1d7-20d3-41d9-a4bd-f4a453434cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/select</value>
      <webElementGuid>cf9831d0-1db0-455a-aece-3f6661bf5c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'tc_status' and @name = 'tc_status' and (text() = 'SelectPending Approval Approved Rejected ' or . = 'SelectPending Approval Approved Rejected ')]</value>
      <webElementGuid>0f99b1e7-9e33-4134-a057-24afa93c1bff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
