<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Requirement Title 1</name>
   <tag></tag>
   <elementGuidId>087623d8-b849-46ae-855d-cb2f968e7425</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='requirement_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#requirement_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>942e0cc9-bae1-45a4-8543-3e3e30814090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>requirement_id</value>
      <webElementGuid>5331bf56-e628-48a6-86f3-e6953b8edab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>requirement_id</value>
      <webElementGuid>bdb749a5-a94f-4032-b67b-6f2307053bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-tns-c127-13 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>5d8264d5-123c-476c-885c-70689c40bb90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Requirement Title 1</value>
      <webElementGuid>d242d72b-327d-40b1-b271-728ab3a8fa3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requirement_id&quot;)</value>
      <webElementGuid>e4fd9577-ff29-4cd0-995d-5a2701bb2cd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='requirement_id']</value>
      <webElementGuid>5549bad1-3439-4ecd-8135-7f9c9a74190f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/select</value>
      <webElementGuid>6c7a226e-719b-4175-80f5-1c2269603e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'requirement_id' and @name = 'requirement_id' and (text() = 'Select Requirement Title 1' or . = 'Select Requirement Title 1')]</value>
      <webElementGuid>9490c69d-6d2f-4fb7-a480-1df7b0c629c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
