<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Bulk update completed successfully</name>
   <tag></tag>
   <elementGuidId>2b515de2-b8c5-4dfc-ad63-950c3fef8095</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toastr-container']/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ng-tns-c1-13.to-message.toastr-message.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>19353cd3-1468-46b0-80bb-bc47e69e4730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c1-13 to-message toastr-message ng-star-inserted</value>
      <webElementGuid>12128e6e-7fe7-4989-94ad-efe06c27e89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bulk update completed successfully</value>
      <webElementGuid>a84eb950-be61-41ec-b11e-da7b6d9e4e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toastr-container&quot;)/div[@class=&quot;ng-trigger ng-trigger-inOut ng-tns-c1-13 toastr toastr-success ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c1-13&quot;]/span[@class=&quot;ng-tns-c1-13 to-message toastr-message ng-star-inserted&quot;]</value>
      <webElementGuid>30041233-18d5-4fbe-9305-a36f8c94d15a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toastr-container']/div/div[2]/span</value>
      <webElementGuid>914bf440-664e-4876-ba11-3f42c7d3896e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>d1bb852a-cbc7-4181-9f29-859ad0c178a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Bulk update completed successfully' or . = 'Bulk update completed successfully')]</value>
      <webElementGuid>f83ea427-74d4-4bd9-b0b8-495c60cc510d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
