<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Browse</name>
   <tag></tag>
   <elementGuidId>e9942a10-f325-4a13-869d-27f79f1dedaa</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.textLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;import_csv_file&quot;]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0a932621-1ca5-4470-8c39-97c47449c209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textLink</value>
      <webElementGuid>a63c3f2d-ad93-4b91-82d4-56a3925bd574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Browse</value>
      <webElementGuid>12a32b80-5cb1-485f-b0dd-7e3e06e53435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography dialog-open&quot;]/app-root[1]/block-ui[1]/app-defect-list[@class=&quot;ng-star-inserted&quot;]/app-layout[1]/div[@class=&quot;ng-main-wrapper&quot;]/div[@class=&quot;content-wrapper ng-star-inserted&quot;]/div[@class=&quot;clearfix&quot;]/div[1]/app-csv-import[1]/app-popup-modal[@class=&quot;ng-star-inserted&quot;]/ngx-smart-modal[1]/div[@class=&quot;overlay ng-star-inserted nsm-overlay-open&quot;]/div[@class=&quot;nsm-dialog nsm-dialog-animation-fade nsm-dialog-open&quot;]/div[@class=&quot;nsm-content&quot;]/div[@class=&quot;nsm-body&quot;]/div[@class=&quot;add_user_model&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;popup_margin_wrapper&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/form[@class=&quot;w-100 ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;form-group&quot;]/app-uploader[1]/div[@class=&quot;uploadFileContainer&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-group w-100&quot;]/div[1]/div[@class=&quot;dropzone&quot;]/div[@class=&quot;text-wrapper&quot;]/label[1]/span[@class=&quot;textLink&quot;]</value>
      <webElementGuid>59ea2c9b-a205-4421-afee-980b01e82a24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/label/span</value>
      <webElementGuid>b526e1ce-521e-4f0d-bcae-08b667806598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '//span[(text() = 'Browse' or . = 'Browse')]')]</value>
      <webElementGuid>705d71bc-2061-47d8-8570-38657a1590ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
