<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_The email address or password that you_4f6311</name>
   <tag></tag>
   <elementGuidId>8dd0f8a7-8c9f-47ff-8bb8-ef15178d8069</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toastr-container']/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ng-tns-c1-0.to-message.toastr-message.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fa6a8a35-742e-4196-a424-538bf1aed19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c1-0 to-message toastr-message ng-star-inserted</value>
      <webElementGuid>4a9deeb5-bb5b-47b4-a96b-6a6c231a2d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The email address or password that you have entered is incorrect.</value>
      <webElementGuid>caa6dc2f-4fea-4bef-93c4-fb37f0455f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toastr-container&quot;)/div[@class=&quot;ng-trigger ng-trigger-inOut ng-tns-c1-0 toastr toastr-error ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c1-0&quot;]/span[@class=&quot;ng-tns-c1-0 to-message toastr-message ng-star-inserted&quot;]</value>
      <webElementGuid>b41f70bb-dd67-46fc-ae18-2ece545a591f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toastr-container']/div/div[2]/span</value>
      <webElementGuid>dd3d9edb-1cbc-4dbf-937b-c9d7d58cb2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>96753d53-b151-499c-80dc-7fcc06a02d09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'The email address or password that you have entered is incorrect.' or . = 'The email address or password that you have entered is incorrect.')]</value>
      <webElementGuid>99bc7e6b-cc9e-4d8a-ac8b-d2cae21c881f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
