<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_2023-12-21</name>
   <tag></tag>
   <elementGuidId>f2a1e613-5428-42c0-bda5-cd4892e0635f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.mat-mdc-cell.mdc-data-table__cell.cdk-cell.dateField.cdk-column-created_on.mat-column-created_on.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>df99ff4f-532a-4285-9b4a-c369f04bc885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-cell mdc-data-table__cell cdk-cell dateField cdk-column-created_on mat-column-created_on ng-star-inserted</value>
      <webElementGuid>dc88f63e-9751-46c3-ab62-34439b915957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>5f48bedc-248e-494e-b57a-962f6a0aff4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2023-12-21</value>
      <webElementGuid>5f191bab-d4f3-4082-be29-9bc696e57257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/block-ui[1]/app-test-case-list[@class=&quot;ng-star-inserted&quot;]/app-layout[1]/div[@class=&quot;ng-main-wrapper&quot;]/div[@class=&quot;content-wrapper ng-star-inserted&quot;]/div[@class=&quot;clearfix&quot;]/div[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;transition-width col-lg-12&quot;]/div[@class=&quot;table_wid&quot;]/div[@class=&quot;siteTableWrapper table-responsive&quot;]/table[@class=&quot;mat-mdc-table mdc-data-table__table cdk-table mat-sort siteTable&quot;]/tbody[@class=&quot;mdc-data-table__content&quot;]/tr[@class=&quot;mat-mdc-row mdc-data-table__row cdk-row position-relative transfarm ng-star-inserted&quot;]/td[@class=&quot;mat-mdc-cell mdc-data-table__cell cdk-cell dateField cdk-column-created_on mat-column-created_on ng-star-inserted&quot;]</value>
      <webElementGuid>e692dcee-4c9a-49a0-b12c-8ead97512660</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]</value>
      <webElementGuid>c7ab2e8d-94db-4ac6-b7b3-8f1547c38926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '2023-12-21' or . = '2023-12-21')]</value>
      <webElementGuid>9781ecfe-35e8-4fdc-86b3-19bab57dc253</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
