<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_summary</name>
   <tag></tag>
   <elementGuidId>0150b9ed-289d-46cd-b225-81f86627833e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='summary']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#summary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>bd64591b-e5ea-4383-9e29-a4ef0d057fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>summary</value>
      <webElementGuid>cd7db8d5-e104-4d50-b6f5-a52dfb39535b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a73241b9-9a27-42d5-99d1-bffc307d4f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>summary</value>
      <webElementGuid>e2bd7678-56d1-4e1d-94ca-c2901e645e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 test-case-form-validation ng-tns-c127-13 ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>81bbec27-f6c3-47e0-a1f5-b7f82c64edcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;summary&quot;)</value>
      <webElementGuid>9c8942a5-3aaf-4f0a-adcb-6037b17bce1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='summary']</value>
      <webElementGuid>9a0377fe-2ef9-4bdb-a286-ec0d46f577e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c2723474-7ca1-4a2b-9ed1-992ebf902f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'summary' and @type = 'text' and @name = 'summary']</value>
      <webElementGuid>f8e9080b-f997-44ac-938b-d3f421b3487c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
